# KMSKeyHandle template
# Replace ${PROJECT_ID}, ${LOCATION}, and ${RESOURCE_TYPE}
# ${RESOURCE_TYPE}: specify which resource types get auto-encrypted (e.g., compute.googleapis.com/Disk)
apiVersion: kms.cnrm.cloud.google.com/v1beta1
kind: KMSKeyHandle
metadata:
  name: kmskeyhandle-sample
spec:
  location: ${LOCATION}
  projectRef:
    external: "projects/${PROJECT_ID}"
  resourceTypeSelector: ${RESOURCE_TYPE}
